name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore D2RSaveMonitor.csproj

    - name: Build Solution (Debug)
      run: dotnet build D2RSaveMonitor.csproj --configuration Debug --no-restore

    - name: Build Solution (Release)
      run: dotnet build D2RSaveMonitor.csproj --configuration Release --no-restore

    - name: Run Code Analysis
      run: dotnet build D2RSaveMonitor.csproj --configuration Debug --no-restore /p:RunCodeAnalysis=true /p:CodeAnalysisTreatWarningsAsErrors=false
      continue-on-error: true

    - name: Upload build artifacts (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: D2RSaveMonitor-Debug
        path: bin/Debug/net8.0-windows/
        retention-days: 7

    - name: Upload build artifacts (Release)
      uses: actions/upload-artifact@v4
      with:
        name: D2RSaveMonitor-Release
        path: bin/Release/net8.0-windows/
        retention-days: 30
